### PR TITLE
💄 Improve appearance of very long layer names (editing toolbox)

### LINKED ISSUE #153: Too Long Toolbox layer title
### Checklist

- [x] I've searched through the existing [issues](../issues) and this bug has never been reported before

### Subject of the issue

In case of long title layer, toolbox title and editing button are showed not aligned

Image

### Steps to reproduce

1. Set long name layer

### Environment

- g3w-admin: __3.9.dev-20250304135044__
- g3w-client: __4.0.0-alpha.0__
- editing: __3.9.0__

### Link to your project

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by volterra79**
Closes: #153 

**Before**

Screenshot_20250305_111646

**After**

Screenshot_20250305_113154

### CODE REVIEW

File: components/Toolbox.vue [hunk 1]
```diff
@@ -38,12 +39,13 @@
...
 
         <!-- PANEL TITLE -->
-        <span class="panel-title">{{ state.title }}</span>
+        <span class = "panel-title">{{ state.title }}</span>
 
         <!-- TOGGLE EDITING -->
         <i
           v-disabled              = "editDisabled"
           @click.stop             = "toggleEditing"
+          style                   = "max-height: 35px; margin-left: auto"
```
Comment (Raruto) [inline components/Toolbox.vue]: @volterra79 `max-height` is necessary? (show me a use case)

Comment (volterra79) [reply components/Toolbox.vue]: @Raruto you are right. it isn't necessary. My mistake

**Review by Raruto — APPROVED** [review]
