### PR TITLE
Handle vector layer relations

### LINKED ISSUE #109: Handle vector layer relations
### Checklist

- [X] I've searched through the existing [issues](../issues) and this bug has never been reported before

### Subject of the issue

Error on handling vector relations

### Steps to reproduce

1. Create a project with two vector layers in relation
2. Add/edit a parent feature
3. Try to update/add a vector relation

### Environment

- g3w-admin: 3.7.7
- g3w-client: 3.9.6

### Link to your project

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by volterra79**
Closes: #109

### CODE REVIEW

File: services/editingservice.js
Comment (Raruto) [inline services/editingservice.js:1]: @volterra79 please let me know if this change might work (ref: `.always((promise) => { promise.always(() => {`)

File: services/relationservice.js [hunk 1]
```diff
@@ -309,17 +311,29 @@ module.exports = class RelationService {
...
-              // relationfeature.isNew())
               featurestore.removeFeature(relationfeature);
-              this.updateParentWorkflows();
+              // check if relation feature delete is new.
+              // In this case, we need to check if there are temporary changes not related to this current feature
+              if (
+                  relationfeature.isNew()
+                  && !WorkflowsStack
+                    ._workflows
+                    .reduce((a,w) => a || w.getSession()._temporarychanges.filter(({ feature }) => relationfeature.getUid() !== feature.getUid()).length > 0, false)
```
Comment (Raruto) [inline services/relationservice.js]: @volterra79 in such cases `Array.Some` it could be more straightforward:

```suggestion
                  && !WorkflowsStack
                     ._workflows
                     .some(w => w.getSession()._temporarychanges.some(({ feature }) => relationfeature.getUid() !== feature.getUid()))
```

Comment (volterra79) [reply services/relationservice.js]: @Raruto fix here https://github.com/g3w-suite/g3w-client-plugin-editing/pull/110/commits/fe59b7b899b40c521d81f53f33405d80592d7a11

Comment (Raruto) [reply services/relationservice.js]: @volterra79 There is something weird:

0. start editing from queryresults

image

1. Create and link a new feature relation (plus icon)
2. click on the save all icon (floppy disk)
3. try delete the new inserted feature (nothing happens)

image
